import { Document, Model, Schema, model } from 'mongoose';
import { ISocialLinks } from '../../common';

export interface EventDocument extends Document {
  title: string;
  description: string;
  additionalInfo?: string;
  socialLinks?: ISocialLinks;
  imageUrl: string;
  typeIds: string[];
  disciplineIds: string[];
  eventDateFrom: number;
  eventDateTo: number;
  status: string;
  isFree: boolean;
  price: number;
  creatorId: string;
  address: string;
  city: string;
  latitude: number;
  longitude: number;
  location?: { type: string; coordinates: number[] };
  seriesId?: string;
  seriesIndex?: number;
  seriesTotal?: number;
  createdAt: number;
  updatedAt?: number;
}

const SocialLinksSchema = new Schema<ISocialLinks>(
  {
    facebook: { type: String, trim: true },
    instagram: { type: String, trim: true },
    pinterest: { type: String, trim: true },
    tiktok: { type: String, trim: true },
    website: { type: String, trim: true },
    whatsapp: { type: String, trim: true },
    youtube: { type: String, trim: true },
  },
  { _id: false },
);

export const EventSchema = new Schema<EventDocument>(
  {
    title: { type: String, required: true, trim: true },
    description: { type: String, required: true, trim: true },
    additionalInfo: { type: String, trim: true },
    socialLinks: { type: SocialLinksSchema },
    imageUrl: { type: String, required: true, trim: true },
    // An event can be more than one type (e.g. workshop then jam) and more
    // than one dance style (e.g. Swing and Rock&Roll), so both are arrays -
    // at least one of each is enforced at the DTO level (ArrayMinSize(1)).
    typeIds: { type: [String], required: true },
    disciplineIds: { type: [String], required: true },
    eventDateFrom: { type: Number, required: true },
    eventDateTo: { type: Number, required: true },
    status: { type: String, required: true },
    isFree: { type: Boolean, required: true, default: false },
    price: { type: Number, required: true, default: 0 },
    creatorId: { type: String, required: true },
    address: { type: String, required: true, trim: true },
    city: { type: String, required: true, trim: true },
    latitude: { type: Number, required: true },
    longitude: { type: Number, required: true },
    location: {
      type: { type: String, enum: ['Point'], default: 'Point' },
      coordinates: { type: [Number], default: [0, 0] },
    },
    // Set together on every instance generated by a recurring-event series
    // (see EventRepository.createSeries) - seriesIndex/seriesTotal are a
    // snapshot taken at creation time, purely for "3 of 12"-style display,
    // not recalculated if instances are later deleted individually.
    seriesId: { type: String },
    seriesIndex: { type: Number },
    seriesTotal: { type: Number },
    createdAt: { type: Number, default: () => Date.now() },
    updatedAt: { type: Number },
  },
  {
    collection: 'events',
    versionKey: false,
  },
);

EventSchema.index({ creatorId: 1 });
EventSchema.index({ disciplineIds: 1 });
EventSchema.index({ typeIds: 1 });
EventSchema.index({ city: 1 });
EventSchema.index({ eventDateFrom: 1 });
EventSchema.index({ location: '2dsphere' });
EventSchema.index({ seriesId: 1 });

export const EventModel: Model<EventDocument> = model<EventDocument>('Event', EventSchema);
