import { Document, Model, Schema, model } from 'mongoose';
import { ISocialLinks } from '../../common';

export interface EventDocument extends Document {
  title: string;
  // Optional because a draft (status: 'draft') can be saved with just a
  // title - these are only guaranteed to be set once status is 'published'
  // (enforced by CreateEventDto/EventService.updateEvent, not the schema).
  description?: string;
  additionalInfo?: string;
  socialLinks?: ISocialLinks;
  imageUrl?: string;
  typeIds?: string[];
  disciplineIds?: string[];
  eventDateFrom?: number;
  eventDateTo?: number;
  status: string;
  isFree: boolean;
  price: number;
  /** Whether attendees (not just the creator/managers) may post gallery
   * photos to this event - defaults on, individually toggleable per event
   * (never propagated across a recurring series, unlike isFree). */
  allowAttendeePhotos: boolean;
  /** 'open': tapping "Asistir" attends immediately (today's only behavior).
   * 'approval': tapping "Asistir" creates a pending join request instead -
   * an accepted manager must approve it (see EventManagerService.
   * requestToJoin/approveJoinRequest/declineJoinRequest) - the organizer can
   * still invite directly either way. Defaults 'open' so every existing
   * event keeps behaving exactly as before. Editable anytime, not just at
   * creation. */
  joinMode: 'open' | 'approval';
  creatorId: string;
  address?: string;
  city?: string;
  latitude?: number;
  longitude?: number;
  location?: { type: string; coordinates: number[] };
  seriesId?: string;
  seriesIndex?: number;
  seriesTotal?: number;
  createdAt: number;
  updatedAt?: number;
}

const SocialLinksSchema = new Schema<ISocialLinks>(
  {
    facebook: { type: String, trim: true },
    instagram: { type: String, trim: true },
    pinterest: { type: String, trim: true },
    tiktok: { type: String, trim: true },
    website: { type: String, trim: true },
    whatsapp: { type: String, trim: true },
    youtube: { type: String, trim: true },
  },
  { _id: false },
);

export const EventSchema = new Schema<EventDocument>(
  {
    title: { type: String, required: true, trim: true },
    // description/imageUrl/typeIds/disciplineIds/eventDateFrom/eventDateTo/
    // address/city/latitude/longitude are only enforced at the DTO level
    // (ValidateIf status !== 'draft') - not required here, since a draft can
    // be saved with just a title and completed later.
    description: { type: String, trim: true },
    additionalInfo: { type: String, trim: true },
    socialLinks: { type: SocialLinksSchema },
    imageUrl: { type: String, trim: true },
    // An event can be more than one type (e.g. workshop then jam) and more
    // than one dance style (e.g. Swing and Rock&Roll), so both are arrays -
    // at least one of each is enforced at the DTO level (ArrayMinSize(1)).
    typeIds: { type: [String] },
    disciplineIds: { type: [String] },
    eventDateFrom: { type: Number },
    eventDateTo: { type: Number },
    status: { type: String, required: true },
    isFree: { type: Boolean, required: true, default: false },
    price: { type: Number, required: true, default: 0 },
    allowAttendeePhotos: { type: Boolean, required: true, default: true },
    joinMode: { type: String, required: true, default: 'open' },
    creatorId: { type: String, required: true },
    address: { type: String, trim: true },
    city: { type: String, trim: true },
    latitude: { type: Number },
    longitude: { type: Number },
    location: {
      type: { type: String, enum: ['Point'], default: 'Point' },
      coordinates: { type: [Number], default: [0, 0] },
    },
    // Set together on every instance generated by a recurring-event series
    // (see EventRepository.createSeries) - seriesIndex/seriesTotal are a
    // snapshot taken at creation time, purely for "3 of 12"-style display,
    // not recalculated if instances are later deleted individually.
    seriesId: { type: String },
    seriesIndex: { type: Number },
    seriesTotal: { type: Number },
    createdAt: { type: Number, default: () => Date.now() },
    updatedAt: { type: Number },
  },
  {
    collection: 'events',
    versionKey: false,
  },
);

EventSchema.index({ creatorId: 1 });
EventSchema.index({ disciplineIds: 1 });
EventSchema.index({ typeIds: 1 });
EventSchema.index({ city: 1 });
EventSchema.index({ eventDateFrom: 1 });
EventSchema.index({ location: '2dsphere' });
EventSchema.index({ seriesId: 1 });

export const EventModel: Model<EventDocument> = model<EventDocument>('Event', EventSchema);
