import { BadRequestException, Controller, Get, Param, Query, Req, Res } from '@nestjs/common';
import type { Request, Response } from 'express';
import sharp from 'sharp';
import { EventService } from './event.service';
import { EventDto } from './event.dto';
import { Public } from '../../common';

/** Link previews (WhatsApp, Telegram, LinkedIn, Facebook...) are generated by
 * each platform's own crawler fetching the shared URL server-side and
 * reading its <meta property="og:..."> tags - they never run JavaScript, so
 * the Angular SPA's own /events/:id page (client-rendered, no per-event
 * meta tags) always previewed as a bare link. This controller serves a tiny
 * static HTML page per event with the real title/description/image in its
 * meta tags for crawlers to read, and immediately redirects real visitors
 * (whose browsers DO run the redirect, unlike crawlers) on to the actual
 * app page. */
function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

// Some crawlers (observed with Facebook's) treat og:url as the content's
// canonical address and re-fetch *that* URL for its own meta tags before
// rendering the card - if og:url pointed at the SPA's bare /events/:id page
// (no server-side meta tags of its own), the crawler would land there and
// throw away everything this page just served. Pointing og:url back at this
// same share page keeps it self-referential, so that re-fetch (if it
// happens) still lands on real event meta tags.
const BOT_USER_AGENT_RE =
  /facebookexternalhit|Facebot|WhatsApp|TelegramBot|Twitterbot|LinkedInBot|Slackbot|Discordbot|Pinterest|redditbot|SkypeUriPreview|vkShare|Applebot|Googlebot|bingbot/i;

const FRONTEND_URL = process.env.FRONTEND_URL ?? 'https://dancemeet-front-8pvn.vercel.app';

// Standard OG/Twitter "large image" card size (1.91:1) - portrait event
// photos (this app's own cover-photo crop is 3:4) get letterboxed onto a
// white canvas at this size instead of served as-is, since some crawlers
// (LinkedIn, Telegram - see shareEventImage) silently drop non-landscape
// og:images rather than cropping/padding them themselves.
const SHARE_IMAGE_WIDTH = 1200;
const SHARE_IMAGE_HEIGHT = 630;

function selfBaseUrl(req: Request): string {
  const forwardedProto = req.headers['x-forwarded-proto'];
  const proto = (Array.isArray(forwardedProto) ? forwardedProto[0] : forwardedProto)?.split(',')[0] ?? req.protocol;
  return `${proto}://${req.get('host')}`;
}

@Controller('share')
@Public()
export class ShareController {
  constructor(private readonly eventService: EventService) {}

  // TinyURL's create endpoint has no auth/API key and returns the short URL
  // as a plain-text body - called from here (not directly from the
  // frontend) purely to sidestep CORS on a third-party domain we don't
  // control. Falls back to the original URL on any failure, so a flaky/down
  // shortener degrades the share text rather than breaking it.
  @Get('shorten')
  async shorten(@Query('url') url?: string): Promise<{ shortUrl: string }> {
    if (!url) {
      throw new BadRequestException('url is required');
    }
    try {
      const response = await fetch(`https://tinyurl.com/api-create.php?url=${encodeURIComponent(url)}`, {
        signal: AbortSignal.timeout(5000),
      });
      const text = (await response.text()).trim();
      if (response.ok && text.startsWith('http')) {
        return { shortUrl: text };
      }
    } catch {
      // fall through to the original URL below
    }
    return { shortUrl: url };
  }

  @Get('events/:id')
  async shareEvent(@Param('id') id: string, @Req() req: Request, @Res() res: Response): Promise<void> {
    const targetUrl = `${FRONTEND_URL}/events/${id}`;
    let event: EventDto;
    try {
      event = await this.eventService.getEventById(id);
    } catch {
      res.redirect(targetUrl);
      return;
    }

    const title = escapeHtml(event.title);
    const description = escapeHtml(event.description).slice(0, 200);
    const url = escapeHtml(targetUrl);
    const base = selfBaseUrl(req);
    const image = escapeHtml(`${base}/share/events/${id}/image`);
    const selfUrl = escapeHtml(`${base}/share/events/${id}`);

    const isBot = BOT_USER_AGENT_RE.test(req.headers['user-agent'] ?? '');
    const redirectTag = isBot ? '' : `<meta http-equiv="refresh" content="0; url=${url}">`;

    res.type('html').send(`<!doctype html>
<html lang="es">
<head>
<meta charset="utf-8">
<title>${title}</title>
<meta name="description" content="${description}">
<meta property="og:type" content="website">
<meta property="og:title" content="${title}">
<meta property="og:description" content="${description}">
<meta property="og:image" content="${image}">
<meta property="og:image:secure_url" content="${image}">
<meta property="og:image:type" content="image/jpeg">
<meta property="og:image:width" content="${SHARE_IMAGE_WIDTH}">
<meta property="og:image:height" content="${SHARE_IMAGE_HEIGHT}">
<meta property="og:url" content="${selfUrl}">
<meta name="twitter:card" content="summary_large_image">
${redirectTag}
</head>
<body>
<p>Redirigiendo a <a href="${url}">${title}</a>...</p>
</body>
</html>`);
  }

  // Letterboxes the event's own photo (any orientation) onto a white
  // 1200x630 landscape canvas - some link-preview crawlers (LinkedIn,
  // Telegram observed) just skip rendering an og:image altogether when it's
  // portrait-oriented rather than cropping/padding it themselves.
  @Get('events/:id/image')
  async shareEventImage(@Param('id') id: string, @Res() res: Response): Promise<void> {
    let event: EventDto;
    try {
      event = await this.eventService.getEventById(id);
    } catch {
      res.status(404).end();
      return;
    }

    try {
      const imageResponse = await fetch(event.imageUrl, { signal: AbortSignal.timeout(8000) });
      if (!imageResponse.ok) {
        throw new Error(`image fetch failed with status ${imageResponse.status}`);
      }
      const original = Buffer.from(await imageResponse.arrayBuffer());
      const resized = await sharp(original)
        .resize(SHARE_IMAGE_WIDTH, SHARE_IMAGE_HEIGHT, { fit: 'inside' })
        .toBuffer();
      const composed = await sharp({
        create: {
          width: SHARE_IMAGE_WIDTH,
          height: SHARE_IMAGE_HEIGHT,
          channels: 3,
          background: { r: 255, g: 255, b: 255 },
        },
      })
        .composite([{ input: resized, gravity: 'center' }])
        .jpeg({ quality: 85 })
        .toBuffer();

      res.set('Cache-Control', 'public, max-age=3600');
      res.type('jpeg').send(composed);
    } catch {
      // Compositing failed (bad/unreachable source image, decode error...) -
      // fall back to the original image straight from Supabase rather than
      // erroring, so the crawler still gets *something*.
      res.redirect(event.imageUrl);
    }
  }
}
